sensor:
  interface:
    description: Main sensor monitoring interface.
    helpLink: sensor.html
    readonly: True
  mtu:
    description: Main IP address of the grid host.
    helpLink: host.html
    readonly: True
